config/routes.rb
Rails.application.routes.draw do
  root "cars#index"
  get "/details" , to: "details#show"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
    has_many_attached :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  include ActiveStorage::SetCurrent

  def index 
    #define fixed points
    fixed_latitude = 21.507989 # Fixed latitude value
    fixed_longitude = 39.218917 # Fixed longitude value

    @cars=Car.all   #to fectch data from model(db) return value will be array

    @nearby_cars= @cars.select do |car|
      distance = calculate_distance(fixed_latitude, fixed_longitude, car.latitiude, car.longitude )
      distance <= 50  
    end  
  end

  def calculate_distance(lat1, long1, lat2, long2)
    r = 6371
    rlat1 = lat1 * Math::PI / 180 #convert to redian
    rlat2 = lat2 * Math::PI / 180 
    deltalat = rlat2-rlat1
    deltalong = (long2 - long1)* Math::PI / 180
    a = Math.sin(deltalat/2) * Math.sin(deltalat/2) +
        Math.cos(rlat1) * Math.cos(rlat2) *
        Math.sin(deltalong/2) * Math.sin(deltalong/2)

    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))      

    d = r * c

  end 

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
    include ActiveStorage::SetCurrent
    
    def show 
        @car = Car.find(params[ :id ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/cars/index.html.erb
<h1>Near cars within 50km </h1>
<ul>
<% @nearby_cars.each do |car|  %>   
  <li> <%= car.make %> <%= car.model %>    
  <img src="<%= car.images.first.url %>" alt="<%= car.make%>" "<%= car.model %> "> 
  <%= link_to "Details", details_path(@show, id: car.id) %>
  </li>
<% end %>
</ul>  

app/views/details/show.html.erb
<h1>Details</h1>
<ul>
<li>Make: <%= @car.make %> </li> 
<li>Model: <%= @car.model%>   </li>
<li>KM: <%= @car.km_travelled %>   </li>
<li>from: <%= @car.available_from.to_date %>   </li>
<li>to: <%= @car.available_to.to_date  %>   </li>
<% @car.images.each do |image|  %>   
    <img src="<%= image.url %>" > 
<% end %>
<ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarRental</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

  </body>
</html>